apiVersion: apps/v1
kind: Deployment
metadata:
  name: practitioner-service
  namespace: medical-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practitioner-service
  template:
    metadata:
      labels:
        app: practitioner-service
    spec:
      containers:
        - name: practitioner-service
          image: practitioner-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka

---
apiVersion: v1
kind: Service
metadata:
  name: practitioner-service
  namespace: medical-office
spec:
  selector:
    app: practitioner-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
